language: python
python:
  - '3.8'

branches:
  only:
    - staging

addons:
  firefox: latest

before_script:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.28.0/geckodriver-v0.28.0-linux64.tar.gz
  - mkdir s_driver
  - tar -xzf geckodriver-v0.28.0-linux64.tar.gz -C s_driver/geckodriver
  - export PATH=$PATH:$PWD/s_driver/geckodriver
  - pip install -r requirements.txt

services:
  - postgresql

env: DJANGO_SETTINGS_MODULE=pur_beurre.travis

script:
  - pytest